
trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: AzureCLI@2
  inputs:
    azureSubscription: 'Azure subscription 1 (ae8cac39-6af7-465e-8ba2-d7d183fa081e)'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      docker build -t akswebapps.azurecr.io/ardela: tag 201-ardela
      az acr login -n akswebapps
      docker push akswebapps.azurecr.io/ardela: tag

- script: cat deploy/kube-app-manager-aio.yaml
- task: Kubernetes@1
  inputs:
    connectionType: 'Azure Resource Manager'
    azureSubscriptionEndpoint: 'aksconnectionpath'
    azureResourceGroup: 'jenkinsrsgrp'
    kubernetesCluster: 'wepabbakscluster'
    namespace: 'default'
    command: 'apply'
    useConfigurationFile: true
    configuration: 'kube-app-manager-aio.yaml'
    secretType: 'dockerRegistry'
    containerRegistryType: 'Azure Container Registry'
    azureSubscriptionEndpointForSecrets: 'aksconnectionpath'
    azureContainerRegistry: 'akswebapps.azurecr.io'
